
[functions.ai-memory]
enabled = true
verify_jwt = false
import_map = "./functions/ai-memory/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-memory/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-memory/*.html" ]

[functions.trip-ai-search]
enabled = true
verify_jwt = false
import_map = "./functions/trip-ai-search/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/trip-ai-search/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/trip-ai-search/*.html" ]

[functions.nearby-ai-recommend]
enabled = true
verify_jwt = false
import_map = "./functions/nearby-ai-recommend/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/nearby-ai-recommend/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/nearby-ai-recommend/*.html" ]

[functions.real-nearby-places]
enabled = true
verify_jwt = false
import_map = "./functions/real-nearby-places/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/real-nearby-places/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/real-nearby-places/*.html" ]

[functions.dashboard-ai-chat]
enabled = true
verify_jwt = false
import_map = "./functions/dashboard-ai-chat/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dashboard-ai-chat/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dashboard-ai-chat/*.html" ]
